### ISSUE TITLE
why can not run demo

### ISSUE THREAD

**Issue by J-Arji** [Jerry-J-Yu/JYDropDownMenu#2]
when i run example error 
`(null): could not read data from '/Users/Javad/Downloads/JYDropDownMenu-master-2/Example/JYDropDownMenu/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.`

**Comment by Jerry-J-Yu** [comment]
Hmm, I cloned it onto a different Mac and couldn't get the demo to work either. Maybe it only works on the Mac I wrote it on.

Try opening the build settings for the JYDropDownMenu_Example, then go to Packaging -> Info.plist File and change the default value of "JYDropDownMenu/Info.plist" to "ProgrammaticallyExample/ProgrammaticallyExample/Info.plist", and see if that does anything.

**Comment by J-Arji** [comment]
no , is wrong

**Comment by Jerry-J-Yu** [comment]
Ok, something must be seriously borked with the example project and I am out of ideas. I suggest taking the "ProgrammaticallyExample" and "StoryboardExample" folders out of the Example folder to make them standalone projects, and do the standard Cocoapods installation process for JYDropDownMenu on each example project.

**Comment by J-Arji** [comment]
no problem , i see then and create own project but It has a problem [#see ](https://github.com/Jerry-J-Yu/JYDropDownMenu/issues/1)
