### ISSUE TITLE
background

### ISSUE THREAD

**Issue by J-Arji** [Jerry-J-Yu/JYDropDownMenu#3]
hi 
when i add comment 
        `self.selectTypeTrain.menuBackgroundColor = UIColor.blueColor()`

error :`Value of type 'JYDropDownMenu' has no member 'menuBackgroundColor'`
why ??

**Comment by Jerry-J-Yu** [comment]
You're right, I made a typo in the readme. It should be `menuTitleBackgroundColor` instead. Thanks for pointing this out and I'll be fixing this now.

**Comment by J-Arji** [comment]
thank you
