### ISSUE TITLE
Is there multiple selection

### ISSUE THREAD

**Issue by jassimkm** [Jerry-J-Yu/JYDropDownMenu#5]
Hi,

is there any way to make multiple selection

**Comment by Jerry-J-Yu** [comment]
In its current form, no. Two problems with multiple selection are that:
- How does the menu know when the user is done selecting the multiple items? You would need a separate "done" button or something of the sort, to make the menu collapse
- What would the label show once the user is done selecting? All of the items' names mashed together, or just the first one, or something else entirely?

In any case, I feel that a more intuitive and visually appealing solution for this problem would be to have a already expanded menu which looks something like the following two images (taken from http://ux.stackexchange.com/questions/87848/what-control-should-i-use-to-indicate-multi-select-lists-on-ios):

![image](https://cloud.githubusercontent.com/assets/6808410/18672748/330283fa-7efe-11e6-85bb-4cc6f61ec35b.png)

![image](https://cloud.githubusercontent.com/assets/6808410/18672639/c51e3172-7efd-11e6-9239-c56b639efea0.png)
